### ISSUE TITLE
onDialNumber Event Not Received on Sequential Task Progression Without Manually Closing Widget

### ISSUE THREAD

**Issue by beaubuehler** [HubSpot/calling-extensions-sdk#237] opened 2024-10-24 07:22 UTC
**Checklist**
- [x] I have read the [FAQs](https://github.com/HubSpot/calling-extensions-sdk#faqs).
- [x] I have checked the [issue tracker](https://github.com/HubSpot/calling-extensions-sdk/issues) for duplicate issues.

**Description**

When starting sequential tasks, the Call Provider Selection Dialog (screenshot below for reference) is initially displayed to the user. Then, after the call button is clicked, the `onDialNumber` event is received. On call completion, the call `callCompleted` message is sent to HubSpot and the widget is successfully closed. 

**When progressing to the next task, the widget is loaded, `resizeWidget` is received, and HubSpot displays the iFrame, but the `onDialNumber` is not received.**

The only way to receive the event is for the user to press the x icon in the widget title bar before clicking the next task (skip or next). Then the Call Provider Selection Dialog is displayed again, call can be pressed, and the onDialNumber is received.

**Expected behavior**
When skipping or pressing next in sequential tasks the `onDialNumber` should be received after it has been hidden using the `callCompleted` message without the user having to press the x icon in the widget title bar.

**To Reproduce**
1. Create call tasks
2. Start call tasks
3. The widget will open showing the Call Provider Selection Dialog. Press call to load the iFrame. After the call send `callCompleted` with `hideWidget = true`
4. Press skip or next to go to the next task
5. The widget will display, but the `onDialNumber` will not be received

**Screenshots/source code**
I may not have accurately named the "Call Provider Selection Dialog" this is what I mean. It is after clicking call that the `onDialNumber` is received.
<img width="205" alt="image" src="https://github.com/user-attachments/assets/de7e0e02-be24-4c0d-958e-ea358d1ee807">

After pressing next, the iFrame loads, but `onDialNumber` is not received.
<img width="281" alt="image" src="https://github.com/user-attachments/assets/2621bbe1-fbba-4ab5-9170-de89c0549adf">

The only way to receive `onDialNumber` is to press the x icon to close the widget before pressing next.
<img width="160" alt="image" src="https://github.com/user-attachments/assets/2399c5a2-3ccc-4756-983a-3a3718ce97c7">

**Device information**

Device: [Macbook Pro M1]
OS: [15.0]
Browser: [Google Chrome]
Browser Version: [129.0.6668.101]

**Comment by esme** [comment] 2024-11-06 20:02
Hi @beaubuehler, thank you for reporting this issue. I am able to reproduce it and have pushed a fix to QA. Would you mind verifying if you're able to receive the dial number event in a day or two?

**Comment by alonso-cadenas** [comment] 2024-11-12 15:59
@beaubuehler, I'll proceed to close the issue since we've released a patch. Please free to reopen if it persists!

**Closed by alonso-cadenas** 2024-11-12 15:59 UTC
Labels: bug
