### ISSUE TITLE
iFrame not initialized to send a message

### ISSUE THREAD

**Issue by uso5** [HubSpot/calling-extensions-sdk#153] opened 2023-10-25 09:17 UTC
**Checklist**
- [X] I have read the [FAQs](https://github.com/HubSpot/calling-extensions-sdk#faqs).
- [X] I have checked the [issue tracker](https://github.com/HubSpot/calling-extensions-sdk/issues) for duplicate issues.

**Description**
When you try to reload iframe manually inside Hubspot you will get the following warning

```iFrame not initialized to send a message {type: 'CALL_ENDED', data: undefined}```

Also sometimes the iFrame is not able to request permission for notifications when reloaded

**Expected behavior**

The iFrame should be somehow able to request resync when reloaded. Is this correct behavior? 

**To Reproduce**

1. Go to https://app.hubspot.com/
2. Click on Reload Frame
4. See iFrame not initialized to send a message...

**Additional context**
This is also happening when doing window.location.assign inside same Iframe host

**Comment by esme** [comment] 2023-11-01 05:01
Hi @uso5, I am not seeing the bug on my end when I reload the iframe. Would you mind clarifying the following:
1. Are you still seeing the warning `iFrame not initialized to send a message {type: 'CALL_ENDED', data: undefined}`? 
2. Are you reloading the iframe inside a third party calling app after selecting the Cloudtalk provider and clicking on the orange call button?

**Comment by uso5** [comment] 2023-11-01 09:23
Hey @esme thanks for reaching out. After upgrading to v0.2.0 we still see this issue. Im sending you screenshare to have it more visible. Is this correct behavior? 


https://github.com/HubSpot/calling-extensions-sdk/assets/1119749/6dacfd6a-e2c8-4fa1-934d-6b38cb8d0782

**Comment by esme** [comment] 2023-11-01 20:48
@uso5 Thank you for sharing the screen recording. I am now able to reproduce the issue and have started working on a fix to address it. Currently, we are re-syncing with the iframe whenever we switch to a new provider but not when it is reloaded. 

After the fix, you should see an `initialized` event once the iframe is reloaded and other events should work accordingly. I should be able to roll out the code changes in a day or two and will let you know as soon as you can begin testing the new behavior.

**Comment by esme** [comment] 2023-11-03 16:11
@uso5 We've deployed the fix to Prod! Let me know if you're still facing issues with the iframe reload.

**Comment by uso5** [comment] 2023-11-06 08:17
@esme Its correct now, thank you!

anyway if we could check also that after some time notification permission stops working in CTI see screenshot. What do you think could be an issue (see logs)? 

![Screenshot 2023-11-06 at 09 14 11](https://github.com/HubSpot/calling-extensions-sdk/assets/1119749/e921e14c-7b0f-456f-9b96-e301b2fe526b)

**Comment by esme** [comment] 2023-11-06 16:59
Hi @uso5, no problem. I'm closing this issue since we've addressed the `iFrame not initialized` warning.

Feel free to open a new issue for the notification permission error and we can follow up there. It looks like the error is happening within the CloudTalk CTI so I have to request the test account credentials to reproduce it and get back to you.

**Closed by esme** 2023-11-06 16:59 UTC
Labels: bug
